language: go
sudo: required
services:
- docker
go: 1.9
after_success: |
  bash <(curl -s https://codecov.io/bash)

  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    make docker-push
  fi
notifications:
  email: false
