language: go
sudo: required
services:
- docker
go : '1.10'
after_success: |
  bash <(curl -s https://codecov.io/bash)

  if [ "${TRAVIS_BRANCH}" == "master" ]; then
    make docker-push
    curl -s -X POST https://goreportcard.com/checks?repo=github.com/ViBiOh/auth
  fi
notifications:
  email: false
