version: '2'

services:
  auth:
    image: vibioh/auth
    command:
    - -corsHeaders
    - Authorization
    - -corsCredentials
    - -githubClientId
    - ${GITHUB_OAUTH_CLIENT_ID}
    - -githubClientSecret
    - ${GITHUB_OAUTH_CLIENT_SECRET}
    - -tracingAgent
    - monitoring_jaeger:6831
    - -tracingName
    - auth
    labels:
      traefik.frontend.passHostHeader: 'true'
      traefik.frontend.rule: 'Host: auth.vibioh.fr'
      traefik.protocol: 'https'
      traefik.port: '1080'
      traefik.frontend.rateLimit.extractorFunc: 'client.ip'
      traefik.frontend.rateLimit.rateSet.first.period: '60s'
      traefik.frontend.rateLimit.rateSet.first.average: '100'
      traefik.frontend.rateLimit.rateSet.first.burst: '200'
    restart: on-failure:5
    read_only: true
    cpu_shares: 128
    mem_limit: 67108864
    security_opt:
    - no-new-privileges

networks:
  default:
    external:
      name: traefik
