[[constraint]]
  branch = "master"
  name = "github.com/ViBiOh/httputils"

[[constraint]]
  branch = "master"
  name = "golang.org/x/crypto"

[[constraint]]
  branch = "master"
  name = "golang.org/x/oauth2"

[[constraint]]
  name = "github.com/manifoldco/promptui"
  version = "0.3.0"

[prune]
  go-tests = true
  unused-packages = true
