// Code generated by "stringer -type=UserKind"; DO NOT EDIT.

package model

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Invite-0]
	_ = x[GitHub-1]
	_ = x[Discord-2]
	_ = x[Basic-3]
	_ = x[Google-4]
}

const _UserKind_name = "InviteGitHubDiscordBasicGoogle"

var _UserKind_index = [...]uint8{0, 6, 12, 19, 24, 30}

func (i UserKind) String() string {
	idx := int(i) - 0
	if i < 0 || idx >= len(_UserKind_index)-1 {
		return "UserKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _UserKind_name[_UserKind_index[idx]:_UserKind_index[idx+1]]
}
